-- MySQL Script generated by MySQL Workbench
-- 06/14/15 16:28:27
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tsystem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tsystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tsystem` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `tsystem` ;

-- -----------------------------------------------------
-- Table `tsystem`.`tbl_typ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tsystem`.`tbl_typ` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tsystem`.`tbl_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tsystem`.`tbl_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(45) NULL,
  `lname` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `tbl_typ_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_user_tbl_typ1_idx` (`tbl_typ_id` ASC),
  CONSTRAINT `fk_tbl_user_tbl_typ1`
    FOREIGN KEY (`tbl_typ_id`)
    REFERENCES `tsystem`.`tbl_typ` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tsystem`.`tbl_priority`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tsystem`.`tbl_priority` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tsystem`.`tbl_ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tsystem`.`tbl_ticket` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titel` VARCHAR(45) NULL,
  `content` VARCHAR(45) NULL,
  `date` VARCHAR(45) NULL,
  `time` VARCHAR(45) NULL,
  `tbl_priority_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_ticket_tbl_priority1_idx` (`tbl_priority_id` ASC),
  CONSTRAINT `fk_tbl_ticket_tbl_priority1`
    FOREIGN KEY (`tbl_priority_id`)
    REFERENCES `tsystem`.`tbl_priority` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tsystem`.`tbl_ticket_has_tbl_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tsystem`.`tbl_ticket_has_tbl_user` (
  `tbl_ticket_id` INT NOT NULL,
  `tbl_user_id` INT NOT NULL,
  PRIMARY KEY (`tbl_ticket_id`, `tbl_user_id`),
  INDEX `fk_tbl_ticket_has_tbl_user_tbl_user1_idx` (`tbl_user_id` ASC),
  INDEX `fk_tbl_ticket_has_tbl_user_tbl_ticket_idx` (`tbl_ticket_id` ASC),
  CONSTRAINT `fk_tbl_ticket_has_tbl_user_tbl_ticket`
    FOREIGN KEY (`tbl_ticket_id`)
    REFERENCES `tsystem`.`tbl_ticket` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_ticket_has_tbl_user_tbl_user1`
    FOREIGN KEY (`tbl_user_id`)
    REFERENCES `tsystem`.`tbl_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
